### ISSUE TITLE
individual should allow for fitness value to be passed in?

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#11]
```
order = POSSIBLE_CARDS
temperature = 1
decay = 0.999

def init_func():
    new_order = POSSIBLE_CARDS[:]
    random.shuffle(new_order)
    return new_order

def eval_func(chromosome):
    return simulate(chromosome, 5)

def accept_prob(score_old, score_new, temperature):
    return math.exp((score_new - score_old) / temperature)
    
def anneal(individual, temperature):
    order, new_order = individual.chromosome[:], individual.chromosome[:]
    random.shuffle(new_order)
    orig_score, new_score = individual.fitness, eval_func(new_order)
    if accept_prob(orig_score, new_score, temperature) > random.random():
        return new_order
    return Individual(order)
```

Simulation is *very* expensive. Am a bit drunk and going out right now in Berlin. Will comment more details tomorrow.

**Comment by koaning** [comment]
It would be nice if I could create an individual and also pass an evaluated fitness to it, in order to prevent a double calculation. Current, I am not able to do that.

**Comment by rogiervandergeer** [comment]
Well that's easy to fix. I'm certainly not against allowing a fitness to be passed when creating an Individual. On the other hand I wonder if what you're doing there shouldn't be done inside the population. Let's discuss

**Comment by rogiervandergeer** [comment]
This has been implemented
