### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#13]
we currently have no documentation, but it needs to be generated somehow.

**Comment by koaning** [comment]
any preference on either of these two tools? 

http://www.sphinx-doc.org/en/stable/
http://pdoc.burntsushi.net/pdoc

**Comment by rogiervandergeer** [comment]
No preference

**Comment by koaning** [comment]
just because it is much faster to implement i propose we go for *pdoc* for now, with the option to go to sphinx later if we feel like it. 

people should read the examples before the documentation anyway.

**Comment by koaning** [comment]
documentation is now up as a service, but we need to still add proper text/images to module descriptions. 

i also fear that we may want to add spaces to docstrings.

**Comment by koaning** [comment]
we have a first version. i will now split this task un into smaller tasks.
