### ISSUE TITLE
plotting = logging

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#15]
This is a place to discuss potential ideas around standardised plotting and logging.

**Comment by koaning** [comment]
So. I'm thinking aloud. We usually want to log the following each time we want to log:

```
timestamp 
generation 
population_id
individual_id 
serialized_chromosome
fitness 
```

I would argue that we want to log all individuals. 

If we agree on *what* to log, it may make it easier to discuss *when* and *how* to log.

**Comment by rogiervandergeer** [comment]
So I've realised that it isn't immediately clear _what_ and _when_ you want to log. So for example you may want iteration / generation, the best fitness (or a distribution of all fitnesses, or quantiles of those distribution if you think storing all might be too much), the best chromosome (or multiple good ones, or all), etc.

Then also, say you have the following evolution:
```
evo = evol.Evolution().survive(0.2).breed(...).mutate()
```
When do you want to log? After the survive? Or after the breed? Or after the mutate? We might say at the beginning, before the survive step. That makes sense.

Now suppose you have something more complicated:

```
evo_1 = evol.Evolution().survive(0.2).breed(...).mutate()
evo_2 = evol.Evolution().survive(0.1).breed(...).mutate()

evo = Evolution().repeat(evo_1, n=25).repeat(evo_2, n=5)
```
Now when do we log? At the start of each iteration of `evo`? Or also inside the `evo_1` and `evo_2`?
My point is, I think we should let the user decide. There is no one way to get this right.


One way of letting the user decide is to introduce a new evolution step: `.log()`. This will tell you exactly _when_ to log, and can accept arguments to tell you _what_ to log. I'm not sure about the underlying details yet (how to implement this, whether `Population` should have the `log()` method as well, and how te separate log files).

**Comment by koaning** [comment]
it feels like having `.log()` makes the most sense and this needs to be a different mechanism than `.checkpoint()`. 

This leaves us to design what we pass into the `.log()` method. Some logging object that should have great flexibility but come with great standard functionality. I imagine something like [and please feel free to shoot at this idea]: 

```
from evol.helpers.loggers import BaseLogger

class Population():
    ....

    def log(logger=BaseLogger()):
        <apply logger>
```

Thoughts? What would be an elegant way for a user to mention where to log things?

**Comment by rogiervandergeer** [comment]
I like that. This way the standard functionality will be that when using
```
evol.Evolution().survive(0.2).breed(...).mutate()
```
nothing will be logged, but that when using
```
evol.Evolution().survive(0.2).breed(...).mutate().log()
```
all the basic and most useful things will be logged.

Now we need to work out the _how_ of the logging. I like the idea of being able to pass a `Logger` object into the `.log` function. This allows us to define multiple `Logger` types, that log to a list, a file, or anything.

On the other hand, it requires more typing from the user: one would need to instantiate a logger and pass it to every `.log()` call there is (which is most likely only one!). Also, the default case would be
a little cumbersome. Suppose we instantiate a logger when none is passed, like so (in your example you made a mutable default argument, which is a bad idea):

```
class Population():
    ....

    def log(logger=None):
        if logger is None: logger = BaseLogger()
        <apply logger>
```

In this case we make a new logger every log event; which is clearly not what we want. 

### Solution 1
What would work, is to store the logger in the population:

```
class Population():
    ....

    def log(logger=None):
        if logger is None:
            if self.logger is None:
                self.logger = BaseLogger()
            logger = self.logger
        <apply logger>
```
In this case, when one uses the default logger the interface is such:
```
evo = Evolution()...()...().log()
pop = Population(...)

pop.apply(evo)

logger = pop.logger
```
while one can use his own by doing:
```
logger = BaseLogger(...)

evo = Evolution()...()...().log(logger)
pop = Population(...)

pop.apply(evo)
```
This works fine as long as you have only one log call. But when you have two, you run into problems:
```
logger = BaseLogger(...)

evo = Evolution()...log()...().log(logger)
pop = Population(...)

pop.apply(evo)
```
This results in us logging to two different loggers. Is that intuitive?

### Solution 2

Alternatively, we can decide to use a global logger as default. 

```
class Population():
    ....

    def log(logger=None):
        if logger is None:
            global GlobalLogger
            logger = GlobalLogger
        <apply logger>
```
In this case, when one uses the default logger the interface is the such:
```
evo = Evolution()...()...().log()
pop = Population(...)

pop.apply(evo)

logger = GlobalLogger
```
while one can use his own by doing:
```
logger = BaseLogger(...)

evo = Evolution()...()...().log(logger)
pop = Population(...)

pop.apply(evo)
```
Also this works fine as long as you have only one log call. But when you have two, you run into problems:
```
logger = BaseLogger(...)

evo = Evolution()...log()...().log(logger)
pop = Population(...)

pop.apply(evo)
```
This results in us logging to two different loggers. Again, is that intuitive?

### Solution 3

We do not allow to pass a `Logger` object to the `log` call. Instead, we associate it with the `Population`. This means that when instantiating a `Population`, a logger can be passed. If none is passed, a default logger will be made. Still, we can use the `.log()` evoluationstep to control _what_ is logged, but the logger decides _where_. Now the default interface is (the same as solution 1):

```
evo = Evolution()...()...().log()
pop = Population(...)

pop.apply(evo)

logger = pop.logger
```
And now one can use his own by doing:
```
logger = BaseLogger(...)

evo = Evolution()...()...().log()
pop = Population(..., logger=logger)

pop.apply(evo)
```

@koaning your opinion?

One last thing: I think loggers should be found in `evol.loggers`.

**Comment by koaning** [comment]
Agreed. Loggers are not helpers. 

Typically you will log the entire population in the same way so it really makes sense to pass some settings to the population object and *not* to the logger method. I like option 3 the best because of this. The nice thing about doing it this way is that this allows us immediately to have a `FileLogger` and a `ListLogger`. 

This does beg a question. Will checkpointing not also have this issue?

**Comment by koaning** [comment]
i've moved part of this discussion to https://github.com/godatadriven/evol/pull/43

**Comment by koaning** [comment]
merged!
