### ISSUE TITLE
Concept of elites

### ISSUE THREAD

**Issue by mattc-eostar** [godatadriven/evol#150]
I searched through the repo looking to see if there is a way to keep elites within the population untouched or accessible to make sure breeding using the top `k` elites to converge to a solution more quickly.

Is this possible with the current implementation? Thanks!

**Comment by koaning** [comment]
I believe this is what `.survive(n=10)` might do. That method allows for a percentage to survive as well as a number. Does this work or is there another aspect to being an 'elite'?

**Comment by rogiervandergeer** [comment]
I guess you may also want to prevent the elites from being mutated. We currently have no such functionality.

On 14 Dec 2019, at 08:00, vincent d warmerdam <notifications@github.com> wrote:

﻿

I believe this is what .survive(n=10) might do. That method allows for a percentage to survive as well as a number. Does this work or is there another aspect to being an 'elite'?

**Comment by koaning** [comment]
Technically ... you can get close. You just have to use the `.breed()` as a proxy for `.mutate`. You would mutate the parents and these would become the new members.
