### ISSUE TITLE
gitlab?

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#151]
github actions seem to have messed up a bunch of things and getting travis back seems to require actions on behalf of the GDD maintainer. 

@rogiervandergeer just a thought. it feels like in this day and age we shouldn't have to tolerate this jankyness from a git provider ... are you opposed to moving this to gitlab?

**Comment by rogiervandergeer** [comment]
I’m pro-gitlab. But it might be good to provide a mirror here

On 14 Dec 2019, at 17:10, vincent d warmerdam <notifications@github.com> wrote:

﻿

github actions seem to have messed up a bunch of things and getting travis back seems to require actions on behalf of the GDD maintainer.

@rogiervandergeer<https://github.com/rogiervandergeer> just a thought. it feels like in this day and age we shouldn't have to tolerate this jankyness from a git provider ... are you opposed to moving this to gitlab?
