### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by rogiervandergeer** [godatadriven/evol#33]
I think the `Population` should have a method to write chromosomes to a file. I've realised that writing entire `Individuals` to file does not work so well, since you may load them into a Population with another fitness function, which will keep you puzzled for hours.

I propose:

`Population.dump(fp)`

`Population.import(fp, **kwargs)` which acts similar to the `generate` classmethod but instead loads from file.

**Comment by rogiervandergeer** [comment]
Or `load` instead of `import`, or `export` instead of `dump`.

**Comment by koaning** [comment]
reminder for self. i propose we call it `.checkpoint()`

**Comment by koaning** [comment]
So for serialisation and checkpointing ... what will be our base method to store a chromosome? Will we always fall back to pickle or might it be better to store the `str(chromosome)` and leave it to the user to implement an `__str__` method if it is a class.

**Comment by rogiervandergeer** [comment]
I'd say we at first we allow for pickle and json. We let the user choose. When they make chromosomes which cannot be handles by one of the two, so be it. After this works it shouldn't be too difficult to let the user define serialisation functions / methods on their chromosome.

**Comment by koaning** [comment]
was this not been merged yet?
