### ISSUE TITLE
Evolutions that evolve populations and populations that evolve following evolutions

### ISSUE THREAD

**Issue by rogiervandergeer** [godatadriven/evol#38]
Currently, our `Evolution` has an `evolve` method; 
```
Evolution.evolve(self, population: Population, n: int=1, inplace=True)
```
Our `Population` also has an `evolve` method:
```
Population.evolve(self, evolution: 'Evolution', n: int = 1)
```

Their functionality is exactly the same, except that the first option can make a copy before evolving. Since these two classes have methods that deal with each other, we run into circular imports. That problems only applies to the typing, so that isn't a real problem, but it's ugly.

I think we should have only one way to do this, i.e. we do allow:
```
evo.evolve(pop)
```

and do not allow
```
pop.evolve(evo)
```

**Comment by koaning** [comment]
I may actually prefer to be able to do `pop = pop.evolve(evo1, n=100).evolve(evo2, n=10)`. If you want to force the `evo.evolve()` then you automatically need to have a third evolution object. 

```
evo1 = Evolution()....
evo2 = Evolution()....

# we now need a third evolution object 
evo3 = Evolution().repeat(evo1, n=100).repeat(evo2, n=10)
evo3.evolve(pop)

# or we don't 
pop = pop.evolve(evo1, n=100).evolve(evo2, n=10)
```

I also personally do not enjoy the inplace updating of `evo3.evolve(pop)`. But this is highly personal.

**Comment by rogiervandergeer** [comment]
I hadn't looked at it like that. I agree that `pop.evolve` is more powerful.

Do you agree that we then remove `Evolution.evolve`?

**Comment by koaning** [comment]
That would be best I think. Less confusion that way.
