### ISSUE TITLE
Cost functions

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#61]
Would we want to have problem instances to be featured in our library as well? It may help people to get started. Say to have cost functions for: 

- easy/hard continous search spaces 
- basic TSP problems 
- 8-queen-like problems

**Comment by rogiervandergeer** [comment]
I do not see any reason why not. I see two options:

- We provide example problems, much like `sklearn.datasets`. This means you can create a problem according to some parameters, but you can not use your own data.
- We provide a function that takes a dataset (for example coordinates) and creates a TSP problem (cost function, and initialisation function) for you. In this case we need to very carefully think about _how_ one would typically want to provide the coordinates.

**Comment by koaning** [comment]
Here is a proposal ... in pseudo fashion. 


```
class Problem():
    ...
class TSPProblem(Problem):
    ...
class TSPUSA(TSPProblem):
    ...

tsp_problem = TSPUSA() # all USA state capitals 
tsp_problem.eval_function
tsp_problem.distance_matrix

tsp_problem = TSPCircle(n_cities=12, radius=1) 
tsp_problem.eval_function
tsp_problem.distance_matrix
```

**Comment by koaning** [comment]
https://github.com/godatadriven/evol/blob/tsp-problems/evol/problems/tsp.py

**Comment by rogiervandergeer** [comment]
I like this! We may also want to implement some initialisation functions, although I'm not sure how to interface that nicely...

**Comment by koaning** [comment]
what about just plain old functions? 

```
chromosomes = [TSPinitializer.heuristic1() for i in range(10)]
```

**Comment by rogiervandergeer** [comment]
That does work! I was thinking a little further ahead. Suppose we expand the `Problem` class to have many specific functions for a certain type of problem, then one would end up doing something like this:

```
p = SomeProblem(...)

pop = Population.generate(init_function=p.heuristic1, eval_function=p.evaluate)

evo = (
    Evolution()
    .survive(0.2)
    .breed(parent_picker=p.parent_picker, combiner=p.combiner)
    .mutate(p.mutate)
)
```
which feels a little redundant. On the other hand it works and for now I do not have any problem with it. More helpers is more better!

**Comment by koaning** [comment]
i think functions might be good enough for now. i do not expect a huge swarm of functions.when we do, we can module it away.

**Comment by koaning** [comment]
the problems branche just got merged. so closing for now.
