### ISSUE TITLE
Helper Algorithms for Initialisation of TSP 

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#62]
Coming up with good candidates can be hard, so I wouldn't mind having some initialisation functions around. 

For travelling salesmen problems though, there's a few heuristics that make sense to have: 

- minimum spanning tree initialisation
- convex hull initialisation
- ... lots ... 

In order to initialise these candidates we may need a place where we can store these helper algorithms. I'd totally love it to implement some of these but I am wondering where to place them. 

@rogiervandergeer opinions?

**Comment by rogiervandergeer** [comment]
I like this idea. I do think that we need to keep with simple algorithms; I do not want to make evol too specific to any problem. 

How about `helpers.initializers`?
