### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#7]
This will be a distracting discussion, my hope is that it will be somewhat humerous though. 

We've already got an awesome title to help with marketing efforts of the package, a next step might include a logo. Let's discuss appropriate options here. 

Here's some suggestions;

- an evil looking dodo bird 
- a group of monkeys evolving into a man with horns 
- a fish with legs

**Comment by rogiervandergeer** [comment]
- Something small evolving into a python

**Comment by koaning** [comment]
Can this be a python with arms and wings?

**Comment by rogiervandergeer** [comment]
Or a python (i.e. the python logo) evolving to have wings?

**Comment by koaning** [comment]
i think i just realised something. 

![image](https://user-images.githubusercontent.com/1019791/33499671-2d4aade4-d6d6-11e7-8395-f2fb2efa278b.png)

**Comment by koaning** [comment]
I've added a bunch of placeholders. Feel free to notify me of something better.
