### ISSUE TITLE
do we want flake8?

### ISSUE THREAD

**Issue by koaning** [godatadriven/evol#87]
After the previous [review](https://github.com/godatadriven/evol/pull/86) I noticed that a lot of the issues could have been caught automatically by a tool like `flake8`. Would we be interested as having that be part of our automated code checks?

**Comment by rogiervandergeer** [comment]
Good idea!

Sent from my iPhone

On 11 Oct 2018, at 20:42, vincent d warmerdam <notifications@github.com<mailto:notifications@github.com>> wrote:


After the previous review I noticed that a lot of the issues could have been caught automatically by a tool like flake8. Would we be interested as having that be part of our automated code checks?

**Comment by koaning** [comment]
oh man. most of the issues are fixed via a pycharm setting. 

**Editor | General | Strip trailing spaces on Save**

**Comment by koaning** [comment]
https://github.com/godatadriven/evol/pull/88
