### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by rogiervandergeer** [godatadriven/evol#93]
In the `helpers` module we have:

```
helpers/
  __init__.py
  _utils.py
  utils.py
  pickers.py
  combiners/
    __init__.py
    _utils.py
    generic.py
    permutation.py
```

These are _three_ utils modules, and most of them are used from multiple locations. I think we should reduce this to at least two.

**Comment by koaning** [comment]
This conversation was indeed bound to happen. 

Maybe we should adhere to a definition. Do we want to have anything in `utils.py` be exposed to a user or is it internal?

**Comment by koaning** [comment]
It seems reasonable that we have one `utils.py` that is used in many parts of the library and that we have `combiners/utils.py` and `whatever/utils.py` files that contain functions that are only used in the submodule. 

about the `_utils.py` vs. `utils.py` ... any strong opinions?

**Comment by rogiervandergeer** [comment]
I've never seen filenames starting with an underscore in any python project (except for `__init__.py` ofc), so I guess `utils.py` would have my preference unless you have a good example.
